require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-minitest

# ruby
Performance:
  Exclude:
    - '**/test/**/*'

Layout/LineLength:
  Max: 160

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/AsciiComments:
  Enabled: false

# rails
AllCops:
  Exclude:
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - 'app/views/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'storage/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'config/**/*'

Bundler/OrderedGems:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*.rb'
